#!/usr/bin/python3
import datetime
import random
import string

num_admins = 3;
num_teachers = 10;
num_substitutes = 20;
num_absences = 50;
basic_password = '0336f0081bc7b681e93679021ae75720e001012f';

school_names = [
	['Lakeside High', 'LSH'], 
	['Matt Wilson Elementary', 'MWE'],
	['Portsmouth Middle', 'PMM'],
	['Westside Middle', 'WSM'],
	['Northeast Junior High', 'NEJH'],
	['Len Lastinger Primary', 'LLP'],
	['Charles Spencer Middle', 'CSM'],
	['JT Reddick Middle', 'JTR'],
	['Bayview Middle', 'BVM']]

street_names = ['East Monroe Ave', 'Jefferson St', 'Fairbanks Ave', 'Portland Blvd', 'West Front St', 'Allen St', 'Bayshore Ave', 'Ocean Dr', 'Washington St', 'Grove St', '6th St', 'Harry Gold Pkwy', 'Julius Thruway', 'Las Venturas Blvd', 'Main St', 'Mulholland Dr', 'W Ellipse Blvd', 'Los Puerta Pkwy', 'Del Perro Blvd']

first_names = ['Awilda', 'Estell', 'Cathryn', 'Leanora', 'Carrol', 'Guy', 'Earline', 'Lupe', 'Jodi', 'Evelina', 'Jong', 'Santina', 'Cody', 'Beaulah', 'Leatha', 'Marvin', 'Doyle', 'Isabella', 'Janet', 'Abe']
last_names = ['Doke', 'Degraff', 'Rode', 'Klocke', 'Prost', 'McGahee', 'Gilmour', 'Schultz', 'Favor', 'Guss', 'Federico', 'Hinerman', 'McMunn', 'Barger', 'Bibee', 'Linderman', 'Brito', 'Westfield', 'Batt', 'Archambault']

print('USE devel')

# clear existing tables
print('TRUNCATE TABLE schools;')
print('TRUNCATE TABLE users;')
print('TRUNCATE TABLE absences;')

# schools
print('INSERT INTO schools (name, abbreviation, street_address) VALUES ')
print(','.join(['("{0}", "{1}", "{2} {3}")'.format(name, abbr, random.randint(101, 9000), random.choice(street_names)) for name, abbr in school_names]))
print(';')

#users
users = []
for i in range(num_admins+num_teachers+num_substitutes):
	role = 'admin' if i < num_admins else 'teacher' if i < num_teachers+num_admins else 'substitute'
	first_name = random.choice(first_names)
	middle_initial = random.choice(string.ascii_uppercase)
	last_name = random.choice(last_names)
	username = first_name[0] + middle_initial.lower() + last_name
	users.append({
		'first_name': first_name,
		'middle_initial': middle_initial,
		'last_name': last_name,
		'role': role,
		'username': username.lower(),
		'password': basic_password,
		'email_address': username.lower() + str(random.randint(3,99)) + "@example.com",
		'primary_phone': '{0}-{1}-{2}'.format(random.randint(100,999), random.randint(100,999), random.randint(1000,9999)),
		'education_level_id': random.randint(1,6),
		'certification': '1969-07-20',
		'school_id': random.randint(1,9),
	})

print('INSERT INTO users (username, password, role, first_name, middle_initial, last_name, email_address, primary_phone, education_level_id, certification, school_id) VALUES ')

print(','.join(['("{0}", "{1}", "{2}", "{3}", "{4}", "{5}", "{6}", "{7}", "{8}", "{9}", "{10}")'.format(
	user['username'],
	user['password'],
	user['role'],
	user['first_name'],
	user['middle_initial'],
	user['last_name'],
	user['email_address'],
	user['primary_phone'],
	user['education_level_id'],
	user['certification'],
	user['school_id']) for user in users]))
print(';')

#absences
absences = []
for i in range(num_absences):
	absentee_id = random.randint(num_admins+1, num_admins+num_teachers)
	fulfiller_id = 'NULL' if random.randint(0,1) > 0 else '"{0}"'.format(random.randint(num_admins+num_teachers+1, num_admins+num_teachers+num_substitutes))
	startdate = datetime.date.today() + datetime.timedelta(days = random.randint(7, 365))
	start = datetime.datetime.combine(startdate, datetime.time(hour=8, minute=(15*random.randint(0,3))))
	end = start + datetime.timedelta(hours = 7, minutes = 15)
	absences.append({
		'absentee_id': absentee_id,
		'fulfiller_id': fulfiller_id,
		'school_id': random.randint(1,9),
		'room': str(random.randint(1, 3)) + str(random.randint(0,5)) + str(random.randint(0, 50)),
		'start': start.isoformat(),
		'end': end.isoformat(),
		'comment': 'autogenerated',
	})

print('ALTER TABLE absences AUTO_INCREMENT = {0};'.format(random.randint(1000,9000)))
print('INSERT INTO absences (absentee_id, fulfiller_id, school_id, room, start, end, comment) VALUES ')

print(','.join(['("{0}", {1}, "{2}", "{3}", "{4}", "{5}", "{6}")'.format(
	absence['absentee_id'],
	absence['fulfiller_id'],
	absence['school_id'],
	absence['room'],
	absence['start'],
	absence['end'],
	absence['comment']) for absence in absences]))
print(';')
